name: crypto_chart_app
description: A minimal Flutter app showing cryptocurrency price chart using CoinGecko and fl_chart.
publish_to: 'none'
version: 0.1.0
environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=2.10.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.6.0
  fl_chart: ^1.1.1
  flutter_riverpod: ^2.3.6
  intl: ^0.17.0
  shared_preferences: ^2.2.0
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
